export const LOAD_GAMES_REQUEST = "LOAD_GAMES_REQUEST";
export const LOAD_GAMES_SUCCESS = "LOAD_GAMES_SUCCESS";
export const LOAD_GAMES_FAILURE = "LOAD_GAMES_FAILURE";

export const CREATE_GAME_REQUEST = "CREATE_GAME_REQUEST";
export const CREATE_GAME_SUCCESS = "CREATE_GAME_SUCCESS";
export const CREATE_GAME_FAILURE = "CREATE_GAME_FAILURE";

export const REMOVE_GAME_REQUEST = "REMOVE_GAME_REQUEST";
export const REMOVE_GAME_SUCCESS = "REMOVE_GAME_SUCCESS";
export const REMOVE_GAME_FAILURE = "REMOVE_GAME_FAILURE";

export const SEARCH_GAMES_REQUEST = "SEARCH_GAMES_REQUEST";
export const SEARCH_GAMES_SUCCESS = "SEARCH_GAMES_SUCCESS";
export const SEARCH_GAMES_FAILURE = "SEARCH_GAMES_FAILURE";

export const GET_GAME_REQUEST = "GET_GAME_REQUEST";
export const GET_GAME_SUCCESS = "GET_GAME_SUCCESS";
export const GET_GAME_FAILURE = "GET_GAME_FAILURE";

export const UPDATE_GAME_REQUEST = "UPDATE_GAME_REQUEST";
export const UPDATE_GAME_SUCCESS = "UPDATE_GAME_SUCCESS";
export const UPDATE_GAME_FAILURE = "UPDATE_GAME_FAILURE";
